version: '3'

networks:
  fastfoodius:


services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fastfoodius
      MYSQL_USER: fastfoodius
      MYSQL_PASSWORD: fastfoodius
    volumes:
      - ./docker/mysql:/var/lib/mysql
    networks:
      - fastfoodius
    ports:
      - "3308:3306"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    environment:
      NODE_ENV: development
      DB_HOST: mysql
      DB_USERNAME: fastfoodius
      DB_PASSWORD: fastfoodius
      DB_DATABASE: fastfoodius
    depends_on:
      - mysql
    command: yarn dev
    ports:
      - "3000:3000"
    networks:
      - fastfoodius

volumes:
  mysql:
