version: '3'

networks:
  my-network:
    driver: bridge

services:
  mysql:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fastnfoodius
      MYSQL_USER: fastnfoodius_user
      MYSQL_PASSWORD: fastnfoodius_pass
    ports:
      - '3306:3306'
    volumes:
      - ./src/database/db.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      timeout: 2s
      retries: 10
    networks:
      - my-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "3000:3000"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - my-network
