version: '3.3'
networks:
  fastnfoodius:


services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fastnfoodius
      MYSQL_USER: fastnfoodius_user
      MYSQL_PASSWORD: fastnfoodius_pass
    ports:
      - '3306:3306'
    networks:
      - fastnfoodius
    expose:
      - '3306'
    volumes:
      # - ./docker/mysql:/var/lib/mysql
      - ./src/database/db.sql:/docker-entrypoint-initdb.d/init.sql
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./:/app
  #   environment:
  #     NODE_ENV: development
  #     DB_HOST: mysql
  #     DB_USERNAME: fastnfoodius_user
  #     DB_PASSWORD: fastnfoodius_pass
  #     DB_DATABASE: fastnfoodius
  #   depends_on:
  #     - mysql
  #   command: yarn dev
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - fastnfoodius

volumes:
  mysql:
